<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Invoice;
use Doctrine\ORM\QueryBuilder;

/**
 * CashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashRepository extends \Doctrine\ORM\EntityRepository
{
 
    public function retrieveLast($nbr)
    {
        $query = $this->createQueryBuilder('c')
            ->orderBy('c.created','desc')
            ->setMaxResults($nbr)    
            ->getQuery();
            return $query->getResult();

    }    

}