<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Invoice;
use Doctrine\ORM\QueryBuilder;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function retrieveAllDraft()
    {
        $query = $this->createQueryBuilder('c')
            ->select('COUNT(c)') 
            ->where('c.status = 0')
            ->getQuery();
            return $query->getSingleScalarResult();

    }      
    
    public function retrieveDraft($nbr)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.status = 0')
            ->orderBy('c.created','ASC')
            ->setMaxResults($nbr)    
            ->getQuery();
            return $query->getResult();

    }     
 
    public function findLastNumber()
    {
        $query = $this->createQueryBuilder('i')            
            ->where('i.credit_number like :year')
            ->setParameters(array('year' => date("y").'%'))
            ->setMaxResults(1)
            ->orderBy('i.credit_number','desc')
            ->getQuery();
            return $query->getOneOrNullResult();

    }    

}