<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Invoice;
use Doctrine\ORM\QueryBuilder;

/**
 * EraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EraseRepository extends \Doctrine\ORM\EntityRepository
{
 
    public function findandRemoveOldNumber($type)
    {
        $query = $this->createQueryBuilder('c')            
            ->where('c.type = :type')
            ->setParameters(array('type' => $type))
            ->setMaxResults(1)
            ->orderBy('c.created','asc')
            ->getQuery();
        
        if ($eraseNumber = $query->getOneOrNullResult()) {
            $old = $eraseNumber->getNumber(); 
            $this->_em->remove($eraseNumber);
            $this->_em->flush();
            
            return $old;
        }
        
        return null;

    }    

}