<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Invoice;
use Doctrine\ORM\QueryBuilder;

/**
 * LogisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogisticRepository extends \Doctrine\ORM\EntityRepository
{
 
    public function retrieveAllActive()
    {
        $query = $this->createQueryBuilder('i')
            ->select('COUNT(i)') 
            ->where('i.checked is null')
            ->getQuery();
            return $query->getSingleScalarResult();

    }   
    
    public function retrieveActive($nbr)
    {
        $query = $this->createQueryBuilder('l')
            ->where('l.checked is null')
            ->orderBy('l.created','ASC')
            ->setMaxResults($nbr)    
            ->getQuery();
            return $query->getResult();

    }    

}