<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Reminder;
use AppBundle\Entity\Invoice;
use Doctrine\ORM\QueryBuilder;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReminderRepository extends \Doctrine\ORM\EntityRepository
{
 
    public function findLastByInvoice(Invoice $invoice)
    {
        $query = $this->createQueryBuilder('r')
            ->where('r.invoice = :invoice')
            ->setParameters(array('invoice' => $invoice))
            ->setMaxResults(1)
            ->orderBy('r.created','desc')
            ->getQuery();
            return $query->getOneOrNullResult();

    }    

}